FROM node:22-alpine3.18

ENV TZ=America/Mexico_City
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apk add --no-cache python3 py3-pip

WORKDIR /usr/local/apps/myapp

COPY package.json ./
RUN npm install && npm cache clean --force
ENV PATH=/usr/local/myapp/node_modules/.bin:$PATH

WORKDIR /usr/local/apps/myapp/dev

COPY src ./src

COPY ./requirements.txt .

# Instala las librerias a usar
RUN pip install -r ./requirements.txt

CMD ["npm", "run", "start:dev"]